package model.pojos;
// Generated 20/06/2017 05:41:39 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * CarrosCompras generated by hbm2java
 */
public class CarrosCompras  implements java.io.Serializable {


     private BigDecimal idCarro;
     private BigDecimal posicionXCarro;
     private BigDecimal posicionYCarro;
     private Set compras = new HashSet(0);

    public CarrosCompras() {
    }

	
    public CarrosCompras(BigDecimal idCarro, BigDecimal posicionXCarro, BigDecimal posicionYCarro) {
        this.idCarro = idCarro;
        this.posicionXCarro = posicionXCarro;
        this.posicionYCarro = posicionYCarro;
    }
    public CarrosCompras(BigDecimal idCarro, BigDecimal posicionXCarro, BigDecimal posicionYCarro, Set compras) {
       this.idCarro = idCarro;
       this.posicionXCarro = posicionXCarro;
       this.posicionYCarro = posicionYCarro;
       this.compras = compras;
    }
   
    public BigDecimal getIdCarro() {
        return this.idCarro;
    }
    
    public void setIdCarro(BigDecimal idCarro) {
        this.idCarro = idCarro;
    }
    public BigDecimal getPosicionXCarro() {
        return this.posicionXCarro;
    }
    
    public void setPosicionXCarro(BigDecimal posicionXCarro) {
        this.posicionXCarro = posicionXCarro;
    }
    public BigDecimal getPosicionYCarro() {
        return this.posicionYCarro;
    }
    
    public void setPosicionYCarro(BigDecimal posicionYCarro) {
        this.posicionYCarro = posicionYCarro;
    }
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }




}


