package model.pojos;
// Generated 20/06/2017 05:41:39 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * CeldaGondola generated by hbm2java
 */
public class CeldaGondola  implements java.io.Serializable {

     private BigDecimal idCelda;
     private BigDecimal productos;
     private BigDecimal gondolas;
     private BigDecimal columnaCelda;
     private BigDecimal filaCelda;
     private BigDecimal cantidadProductoCelda;

    public CeldaGondola() {
    }
	
    public CeldaGondola(BigDecimal idCelda, BigDecimal gondolas, BigDecimal columnaCelda, BigDecimal filaCelda, BigDecimal cantidadProductoCelda) {
        this.idCelda = idCelda;
        this.gondolas = gondolas;
        this.columnaCelda = columnaCelda;
        this.filaCelda = filaCelda;
        this.cantidadProductoCelda = cantidadProductoCelda;
    }
    public CeldaGondola(BigDecimal idCelda, BigDecimal productos, BigDecimal gondolas, BigDecimal columnaCelda, BigDecimal filaCelda, BigDecimal cantidadProductoCelda) {
       this.idCelda = idCelda;
       this.productos = productos;
       this.gondolas = gondolas;
       this.columnaCelda = columnaCelda;
       this.filaCelda = filaCelda;
       this.cantidadProductoCelda = cantidadProductoCelda;
    }
   
    public BigDecimal getIdCelda() {
        return this.idCelda;
    }
    
    public void setIdCelda(BigDecimal idCelda) {
        this.idCelda = idCelda;
    }
    public BigDecimal getProductos() {
        return this.productos;
    }
    
    public void setProductos(BigDecimal productos) {
        this.productos = productos;
    }
    public BigDecimal getGondolas() {
        return this.gondolas;
    }
    
    public void setGondolas(BigDecimal gondolas) {
        this.gondolas = gondolas;
    }
    public BigDecimal getColumnaCelda() {
        return this.columnaCelda;
    }
    
    public void setColumnaCelda(BigDecimal columnaCelda) {
        this.columnaCelda = columnaCelda;
    }
    public BigDecimal getFilaCelda() {
        return this.filaCelda;
    }
    
    public void setFilaCelda(BigDecimal filaCelda) {
        this.filaCelda = filaCelda;
    }
    public BigDecimal getCantidadProductoCelda() {
        return this.cantidadProductoCelda;
    }
    
    public void setCantidadProductoCelda(BigDecimal cantidadProductoCelda) {
        this.cantidadProductoCelda = cantidadProductoCelda;
    }




}


