package model.pojos;
// Generated 20/06/2017 05:41:39 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private BigDecimal idCliente;
     private String nombreCliente;
     private String apellidoCliente;
     private String correoElectronicoCliente;
     private BigDecimal telefonoCliente;
     private Set compras = new HashSet(0);
     private Set listadeseoses = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(BigDecimal idCliente, String nombreCliente, String apellidoCliente, String correoElectronicoCliente) {
        this.idCliente = idCliente;
        this.nombreCliente = nombreCliente;
        this.apellidoCliente = apellidoCliente;
        this.correoElectronicoCliente = correoElectronicoCliente;
    }
    public Cliente(BigDecimal idCliente, String nombreCliente, String apellidoCliente, String correoElectronicoCliente, BigDecimal telefonoCliente, Set compras, Set listadeseoses) {
       this.idCliente = idCliente;
       this.nombreCliente = nombreCliente;
       this.apellidoCliente = apellidoCliente;
       this.correoElectronicoCliente = correoElectronicoCliente;
       this.telefonoCliente = telefonoCliente;
       this.compras = compras;
       this.listadeseoses = listadeseoses;
    }
   
    public BigDecimal getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(BigDecimal idCliente) {
        this.idCliente = idCliente;
    }
    public String getNombreCliente() {
        return this.nombreCliente;
    }
    
    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }
    public String getApellidoCliente() {
        return this.apellidoCliente;
    }
    
    public void setApellidoCliente(String apellidoCliente) {
        this.apellidoCliente = apellidoCliente;
    }
    public String getCorreoElectronicoCliente() {
        return this.correoElectronicoCliente;
    }
    
    public void setCorreoElectronicoCliente(String correoElectronicoCliente) {
        this.correoElectronicoCliente = correoElectronicoCliente;
    }
    public BigDecimal getTelefonoCliente() {
        return this.telefonoCliente;
    }
    
    public void setTelefonoCliente(BigDecimal telefonoCliente) {
        this.telefonoCliente = telefonoCliente;
    }
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }
    public Set getListadeseoses() {
        return this.listadeseoses;
    }
    
    public void setListadeseoses(Set listadeseoses) {
        this.listadeseoses = listadeseoses;
    }




}


