package model.pojos;
// Generated 20/06/2017 05:41:39 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Detalles generated by hbm2java
 */
public class Detalles  implements java.io.Serializable {


     private BigDecimal idDetalle;
     private BigDecimal productos;
     private BigDecimal compra;
     private BigDecimal cantidadProducto;

    public Detalles() {
    }

    public Detalles(BigDecimal idDetalle, BigDecimal productos, BigDecimal compra, BigDecimal cantidadProducto) {
       this.idDetalle = idDetalle;
       this.productos = productos;
       this.compra = compra;
       this.cantidadProducto = cantidadProducto;
    }
   
    public BigDecimal getIdDetalle() {
        return this.idDetalle;
    }
    
    public void setIdDetalle(BigDecimal idDetalle) {
        this.idDetalle = idDetalle;
    }
    public BigDecimal getProductos() {
        return this.productos;
    }
    
    public void setProductos(BigDecimal productos) {
        this.productos = productos;
    }
    public BigDecimal getCompra() {
        return this.compra;
    }
    
    public void setCompra(BigDecimal compra) {
        this.compra = compra;
    }
    public BigDecimal getCantidadProducto() {
        return this.cantidadProducto;
    }
    
    public void setCantidadProducto(BigDecimal cantidadProducto) {
        this.cantidadProducto = cantidadProducto;
    }




}


