package model.pojos;
// Generated 20/06/2017 05:41:39 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Gondolas generated by hbm2java
 */
public class Gondolas  implements java.io.Serializable {


     private BigDecimal idGondola;
     private BigDecimal nivelesGondola;
     private BigDecimal posicionXGondola;
     private BigDecimal posicionYGondola;

    public Gondolas() {
    }

	
    public Gondolas(BigDecimal idGondola, BigDecimal nivelesGondola, BigDecimal posicionXGondola, BigDecimal posicionYGondola) {
        this.idGondola = idGondola;
        this.nivelesGondola = nivelesGondola;
        this.posicionXGondola = posicionXGondola;
        this.posicionYGondola = posicionYGondola;
    }

   
    public BigDecimal getIdGondola() {
        return this.idGondola;
    }
    
    public void setIdGondola(BigDecimal idGondola) {
        this.idGondola = idGondola;
    }
    public BigDecimal getNivelesGondola() {
        return this.nivelesGondola;
    }
    
    public void setNivelesGondola(BigDecimal nivelesGondola) {
        this.nivelesGondola = nivelesGondola;
    }
    public BigDecimal getPosicionXGondola() {
        return this.posicionXGondola;
    }
    
    public void setPosicionXGondola(BigDecimal posicionXGondola) {
        this.posicionXGondola = posicionXGondola;
    }
    public BigDecimal getPosicionYGondola() {
        return this.posicionYGondola;
    }
    
    public void setPosicionYGondola(BigDecimal posicionYGondola) {
        this.posicionYGondola = posicionYGondola;
    }




}


