package model.pojos;
// Generated 20/06/2017 05:41:39 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Listadeseos generated by hbm2java
 */
public class Listadeseos  implements java.io.Serializable {


     private BigDecimal idListadeseo;
     private Cliente cliente;
     private Date fechaGenerada;
     private Set productoses = new HashSet(0);

    public Listadeseos() {
    }

	
    public Listadeseos(BigDecimal idListadeseo, Cliente cliente, Date fechaGenerada) {
        this.idListadeseo = idListadeseo;
        this.cliente = cliente;
        this.fechaGenerada = fechaGenerada;
    }
    public Listadeseos(BigDecimal idListadeseo, Cliente cliente, Date fechaGenerada, Set productoses) {
       this.idListadeseo = idListadeseo;
       this.cliente = cliente;
       this.fechaGenerada = fechaGenerada;
       this.productoses = productoses;
    }
   
    public BigDecimal getIdListadeseo() {
        return this.idListadeseo;
    }
    
    public void setIdListadeseo(BigDecimal idListadeseo) {
        this.idListadeseo = idListadeseo;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Date getFechaGenerada() {
        return this.fechaGenerada;
    }
    
    public void setFechaGenerada(Date fechaGenerada) {
        this.fechaGenerada = fechaGenerada;
    }
    public Set getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set productoses) {
        this.productoses = productoses;
    }




}


