package model.pojos;
// Generated 20/06/2017 05:41:39 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Marcas generated by hbm2java
 */
public class Marcas  implements java.io.Serializable {


     private BigDecimal idMarca;
     private String nombreMarca;
     private Set productoses = new HashSet(0);

    public Marcas() {
    }

	
    public Marcas(BigDecimal idMarca, String nombreMarca) {
        this.idMarca = idMarca;
        this.nombreMarca = nombreMarca;
    }
    public Marcas(BigDecimal idMarca, String nombreMarca, Set productoses) {
       this.idMarca = idMarca;
       this.nombreMarca = nombreMarca;
       this.productoses = productoses;
    }
   
    public BigDecimal getIdMarca() {
        return this.idMarca;
    }
    
    public void setIdMarca(BigDecimal idMarca) {
        this.idMarca = idMarca;
    }
    public String getNombreMarca() {
        return this.nombreMarca;
    }
    
    public void setNombreMarca(String nombreMarca) {
        this.nombreMarca = nombreMarca;
    }
    public Set getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set productoses) {
        this.productoses = productoses;
    }




}


