package model.pojos;
// Generated 20/06/2017 05:41:39 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private BigDecimal idProducto;
     private String marcas;
     private String nombreProducto;
     private BigDecimal precioProducto;
     private String descripcionProducto;
     private Date fechavencimientoProducto;
     private String tipoProducto;
     private BigDecimal cantidadProducto;
     private String medidaProducto;
     private BigDecimal cantidadMedidaProducto;
//     private String descripcion;
//     private Serializable fechaVencimiento;
//     private String name;
//     private Set listadeseoses = new HashSet(0);
//     private Set detalleses = new HashSet(0);
//     private Set celdaGondolas = new HashSet(0);

    public Productos() {
    }

	
    public Productos(BigDecimal idProducto, String marcas, String nombreProducto, BigDecimal precioProducto, String descripcionProducto, String tipoProducto, BigDecimal cantidadProducto, String medidaProducto, BigDecimal cantidadMedidaProducto) {
        this.idProducto = idProducto;
        this.marcas = marcas;
        this.nombreProducto = nombreProducto;
        this.precioProducto = precioProducto;
        this.descripcionProducto = descripcionProducto;
        this.tipoProducto = tipoProducto;
        this.cantidadProducto = cantidadProducto;
        this.medidaProducto = medidaProducto;
        this.cantidadMedidaProducto = cantidadMedidaProducto;
    }
//    public Productos(BigDecimal idProducto, Marcas marcas, String nombreProducto, BigDecimal precioProducto, String descripcionProducto, Date fechavencimientoProducto, String tipoProducto, BigDecimal cantidadProducto, String medidaProducto, BigDecimal cantidadMedidaProducto, String descripcion, Serializable fechaVencimiento, String name, Set listadeseoses, Set detalleses, Set celdaGondolas) {
//       this.idProducto = idProducto;
//       this.marcas = marcas;
//       this.nombreProducto = nombreProducto;
//       this.precioProducto = precioProducto;
//       this.descripcionProducto = descripcionProducto;
//       this.fechavencimientoProducto = fechavencimientoProducto;
//       this.tipoProducto = tipoProducto;
//       this.cantidadProducto = cantidadProducto;
//       this.medidaProducto = medidaProducto;
//       this.cantidadMedidaProducto = cantidadMedidaProducto;
////       this.descripcion = descripcion;
////       this.fechaVencimiento = fechaVencimiento;
////       this.name = name;
////       this.listadeseoses = listadeseoses;
////       this.detalleses = detalleses;
////       this.celdaGondolas = celdaGondolas;
//    }
   
    public BigDecimal getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(BigDecimal idProducto) {
        this.idProducto = idProducto;
    }
    public String getMarcas() {
        return this.marcas;
    }
    
    public void setMarcas(String marcas) {
        this.marcas = marcas;
    }
    public String getNombreProducto() {
        return this.nombreProducto;
    }
    
    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }
    public BigDecimal getPrecioProducto() {
        return this.precioProducto;
    }
    
    public void setPrecioProducto(BigDecimal precioProducto) {
        this.precioProducto = precioProducto;
    }
    public String getDescripcionProducto() {
        return this.descripcionProducto;
    }
    
    public void setDescripcionProducto(String descripcionProducto) {
        this.descripcionProducto = descripcionProducto;
    }
    public Date getFechavencimientoProducto() {
        return this.fechavencimientoProducto;
    }
    
    public void setFechavencimientoProducto(Date fechavencimientoProducto) {
        this.fechavencimientoProducto = fechavencimientoProducto;
    }
    public String getTipoProducto() {
        return this.tipoProducto;
    }
    
    public void setTipoProducto(String tipoProducto) {
        this.tipoProducto = tipoProducto;
    }
    public BigDecimal getCantidadProducto() {
        return this.cantidadProducto;
    }
    
    public void setCantidadProducto(BigDecimal cantidadProducto) {
        this.cantidadProducto = cantidadProducto;
    }
    public String getMedidaProducto() {
        return this.medidaProducto;
    }
    
    public void setMedidaProducto(String medidaProducto) {
        this.medidaProducto = medidaProducto;
    }
    public BigDecimal getCantidadMedidaProducto() {
        return this.cantidadMedidaProducto;
    }
    
    public void setCantidadMedidaProducto(BigDecimal cantidadMedidaProducto) {
        this.cantidadMedidaProducto = cantidadMedidaProducto;
    }
//    public String getDescripcion() {
//        return this.descripcion;
//    }
//    
//    public void setDescripcion(String descripcion) {
//        this.descripcion = descripcion;
//    }
//    public Serializable getFechaVencimiento() {
//        return this.fechaVencimiento;
//    }
//    
//    public void setFechaVencimiento(Serializable fechaVencimiento) {
//        this.fechaVencimiento = fechaVencimiento;
//    }
//    public String getName() {
//        return this.name;
//    }
//    
//    public void setName(String name) {
//        this.name = name;
//    }
//    public Set getListadeseoses() {
//        return this.listadeseoses;
//    }
//    
//    public void setListadeseoses(Set listadeseoses) {
//        this.listadeseoses = listadeseoses;
//    }
//    public Set getDetalleses() {
//        return this.detalleses;
//    }
//    
//    public void setDetalleses(Set detalleses) {
//        this.detalleses = detalleses;
//    }
//    public Set getCeldaGondolas() {
//        return this.celdaGondolas;
//    }
//    
//    public void setCeldaGondolas(Set celdaGondolas) {
//        this.celdaGondolas = celdaGondolas;
//    }




}


